# local.docker
server:
  port: 8080

spring.liquibase.contexts: development

springdoc.swagger-ui.enabled: true

logging.level:
  by:
    sorface:
      passport:
        web:
          security:
            config: DEBUG
  org:
    springframework:
      security:
        web: ERROR
      web:
        servlet: ERROR
        cors: TRACE

  root: error
