application:
  metadata:
    version: ${APPLICATION_METADATA_VERSION}

spring:
  application:
    name: sorface-passport
  banner:
    location: classpath:banner.txt

  config:
    import:
      - classpath:imports/passport.smtp.yml
      - classpath:imports/passport.datasource.yml
      - classpath:imports/passport.session.yml
      - classpath:imports/passport.security.yml
      - classpath:imports/passport.redirect.yml
      - classpath:imports/passport.account.yml

  cloud:
    compatibility-verifier:
      enabled: false

  sleuth:
    enabled: true

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:static

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: error
    nl.basjes.parse: error
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} %highlight(%-5level) [%blue(%X{traceId:-})|%green(%X{spanId})] [%thread] %magenta([%file:%line]) : %msg%n'
