server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,env
  observations:
    annotations:
      enabled: true

spring:
  application:
    name: sorface-passport-backend
    version: 1.0.0

  data.redis:
    client-type: jedis
    database: 5
    host: localhost
    port: 6379
    username: default
    password: testpassword
    jedis.pool:
      max-active: 100
      max-idle: 15

  datasource:
    url: "*****"
    username: "username"
    password: "password"
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  session:
    timeout: 5d
    redis:
      flush-mode: on_save
      namespace: "passport"
      save-mode: on_set_attribute
      repository-type: indexed
      cleanup-cron: 0 * * * * *
      configure-action: notify_keyspace_events

  liquibase:
    contexts:
      - production
    change-log: migration/master.yaml
    enabled: true

  mail:
    username: '****************'
    password: '****************'
    port: 465
    host: smtp.yandex.ru
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  graphql:
    graphiql:
      enabled: false
      path: /graphiql

  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: '************'
            client-secret: '************'

          yandex:
            client-name: yandex
            client-id: '************'
            client-secret: '************'
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: '************'

          twitch:
            client-name: twitch
            client-id: '************'
            client-secret: '************'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - user:read:email
            provider: twitch
            redirect-uri: '************'

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            userInfoUri: https://api.twitch.tv/helix/users/
            user-info-authentication-method: GET
            user-name-attribute: data

idp:
  cors:
    allowed-origins:
      - 'https://passport.sorface.ru'
      - 'https://api.gateway.sorface.ru'
      - 'https://interview.sorface.ru'
      - 'https://id.sorface.ru'
    allowCredentials: true

  cookie:
    session:
      domainpattern: '^.+?\.(\w+\.[a-z]+)$'
      path: '/'
      name: 'pspt_sid'
      httponly: true
      same-site: lax
      secure: true

    csrf:
      name: 'x_csrf_token'
      domain: 'sorface.com'
      path: '/'
      httponly: false
      secure: true

    registration:
      name: 'registrationId'
      domain: 'sorface.com'
      path: '/'
      httponly: true
      secure: true
      maxage: 600

    otpexpat:
      name: 'otp_exp_time'
      domain: 'sorface.com'
      path: '/'
      httponly: false
      secure: false
      maxage: 120

  oidc:
    url: http://localhost:${server.port}

  endpoint:
    login-path: '/api/login'
    frontend:
      account-page: 'http://localhost:9030/account'

logging:
  level:
    root: info
    by.sorface.idp: info
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} %highlight(%-5level) [%thread] [${spring.application.name:},%X{traceId:-}, %X{spanId:-}]%magenta([%file:%line]) : %msg%n'
  include-application-name: false

--- # spring development envs

spring:
  config:
    activate:
      on-profile: development

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:idp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;"
    username: "username"
    password: "password"
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    contexts:
      - development
    change-log: migration/master.yaml
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

--- # spring development envs

spring:
  config:
    activate:
      on-profile: sandbox

  mail:
    username: '****************'
    password: '****************'

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/idp
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    contexts:
      - development
    change-log: migration/master.yaml
    enabled: true

idp:
  cors:
    allowed-origins:
      - 'http://localhost:9020'
      - 'http://localhost:9030'
    allowCredentials: true

  cookie:
    session:
      domainpattern: '^.+?\.(\w+\.[a-z]+)$'
      path: '/'
      name: 'pspt_sid'
      httponly: true
      same-site: lax
      secure: false

    csrf:
      name: 'x_csrf_token'
      domain: 'localhost'
      path: '/'
      httponly: false
      secure: false

    registration:
      name: 'registrationId'
      domain: 'localhost'
      path: '/'
      httponly: true
      secure: false
      maxage: 600

    otpexpat:
      name: 'localhost'
      domain: 'sorface.com'
      path: '/'
      httponly: false
      secure: false
      maxage: 120

logging:
  level:
    by.sorface.idp: debug
    root: info
    by.sorface.idp.config.web.autostart: debug
