name: helm chart deployment [release]

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: "Release branch. В данную веткой создастся PR в репозитории"
      chart-repository:
        required: true
        type: string
      chart-image-name:
        required: true
        type: string
      chart-image-tag:
        required: true
        type: string
      json:
        required: true
        type: string
    secrets:
      GIT_TOKEN:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка исходного кода Helm Chart
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.chart-repository }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: echo values.yaml
        run: |
          cat sorface/values.yaml

      - name: Обновление версии сервиса в values Helm Chart
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          valueFile: 'sorface/values.yaml'
          format: 'YAML'
          commitChange: true
          title: ${{format('release deployment for {0} - {1}', inputs.chart-image-name, inputs.branch)}}
          message: ${{format('release deployment for {0} - {1}', inputs.chart-image-name, inputs.branch)}}
          repository: ${{ inputs.chart-repository }}
          branch: ${{format('deployment/{0}', inputs.branch)}}
          targetBranch: ${{ inputs.branch }}
          createPR: true
          changes: ${{ inputs.json }}
