name: helm chart deployment [release]

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      chart-image-name:
        required: true
        type: string
      chart-image-tag:
        required: true
        type: string

    secrets:
      GIT_TOKEN:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка исходного кода chart
        uses: actions/checkout@v4
        with:
          repository: sorface/prod2-chart
          token: ${{ secrets.GIT_TOKEN }}

      - name: Отображение values.yaml
        run: |
          cat sorface/values.yaml

      - name: Обновление версии Image и создание PR
        uses: fjogeleit/yaml-update-action@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          valueFile: 'sorface/values.yaml'
          format: 'YAML'
          commitChange: true
          title: ${{format('Update deployment for {0}', inputs.branch)}}
          message: ${{format('release deployment for {0} - {1}', inputs.chart-image-name, inputs.branch)}}
          repository: sorface/prod-chart
          branch: ${{format('deployment/{0}', inputs.branch)}}
          targetBranch: ${{ inputs.branch }}
          createPR: true
          changes: |
            {
              "${{inputs.chart-image-name}}.imageName": "${{inputs.chart-image-name}}",
              "${{inputs.chart-image-name}}.imageTag": "${{ inputs.chart-image-tag }}",
            }