name: Создание релиза
run-name: sorface idp [${{ format('{0}-{1}', github.event.inputs.branch,  github.event.inputs.version) }}]

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        description: 'Тип релиза'
        default: 'beta'
        options:
          - beta
          - alpha
          - final
      version:
        required: true
        type: string
        description: 'Версия релиза в формате X.X.X'

jobs:

  release-branch:
    name: Формирование и создание релизной ветки
    uses: sorface/passport/.github/workflows/sys_wc_release-branch.yaml@master

    with:
      repository: passport
      main-branch: ${{ github.head_ref }}
      tag: ${{ format('{0}-{1}', github.event.inputs.version,  github.event.inputs.release-type) }}

    secrets: inherit

  passport:
    name: Загрузка исходного кода, сборка и формирование Docker Image

    uses: sorface/passport/.github/workflows/wc_deploy.yaml@master

    needs: [ release-branch ]

    with:
      branch: ${{ needs.release-branch.outputs.branch }}
      version: ${{ format('{0}-{1}', github.event.inputs.version,  github.event.inputs.release-type) }}
      yc-image-repository-id: 'crpmbctb3d161aoorvrk'
      yc-image-package-name: 'be_passport'

    secrets: inherit

  chart-release-branch:
    name: Создание релизной ветки для Helm Chart
    uses: sorface/passport/.github/workflows/sys_wc_release-branch.yaml@master

    needs: [ release-branch, passport ]

    with:
      repository: prod2-chart
      main-branch: master
      tag: ${{ format('be_passport-v{0}-{1}', github.event.inputs.version,  github.event.inputs.release-type) }}

    secrets: inherit

  update-deployment-helm-chart:
    name: Обновление Helm Chart
    uses: sorface/passport/.github/workflows/sys_wc_helm-chart.yaml@master

    needs:
      - chart-release-branch

    with:
      branch: ${{ needs.chart-release-branch.outputs.branch }}
      chart-repository: sorface/prod2-chart
      chart-image-name: be_passport
      chart-image-tag: ${{ format('{0}-{1}', github.event.inputs.version,  github.event.inputs.release-type) }}
      json: |
        {
          "be_passport.imageName": "be_passport",
          "be_passport.imageTag": "${{ format('{0}-{1}', github.event.inputs.version,  github.event.inputs.release-type) }}"
        }
    secrets: inherit
